#项目端口配置
server:
  port: 8080
  servlet:
    context-path: /aaa

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://192.168.126.131:33306/myproject
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#mybatis配置文件的路径
#mybatis:
 # mapper-locations: classpath:mapper/*.xml

